import type { Metadata } from "next";
import {
  Geist,
  Geist_Mono,
  Metal_Mania,
  Michroma,
  Poppins,
} from "next/font/google";
import "./global.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});
const metalMania = Metal_Mania({
  subsets: ["latin"], // include only the subsets you need
  weight: "400", // Metal Mania only has one weight
  variable: "--font-metal-mania",
});

const michroma = Michroma({
  subsets: ["latin"],
  weight: "400", // Michroma only has one weight
  variable: "--font-michroma",
});

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "500", "700"],
  variable: "--font-poppins",
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={poppins.className}>
      <body>{children}</body>
    </html>
  );
}
